---
title       : Data uploading and Metadata editing
subtitle    : 15 Feb - 08 Mar 2013 - Summary stats
author      : Marco Bascietto, Giorgio Matteucci
job         : EnvEurope A5 "Testing in the Field" - Use arrows to move between slides
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
github:
  user: mbask
  repo: A5DataUpload
---

```{r "initialize", echo=FALSE, result=FALSE, warning=FALSE, cache=FALSE, include=FALSE}
setwd("~/Documents/Academy/IBAF/ENVEUROPE/A5/DataUpload/A5-DataAndMetadataUpload")
rm(list = ls())

source("../include/DBSetup.R")
source("../include/functions.R")
figName <- "A5DAMU-1"
opts_chunk$set(
  fig.path = paste0("figure/", figName)
  , fig.width = 13
  , fig.height = 7
  , cache = FALSE
  , echo=FALSE
  )


library(plyr)
library(ggplot2)
library(lubridate)
library(xtable)
library(sqlutils)
sqlPaths("~/Documents/Academy/IBAF/ENVEUROPE/A5/DataUpload/SQL")
library(googleVis)
gVisOp <- options(gvis.plot.tag='chart')

submissionWindowDates <- list(
  start = as.Date("2013-02-15")
  , end = as.Date("2013-03-08")
  )


dbConnection <- with(db.sqlite.cfg, dbConnect(driver, dbname = fName))

# Get submission date from each year 2011 and 2012 parameter 
param_wdf <- execQuery('parameterSubmittedStatus', connection = dbConnection)

param_wdf <- within(param_wdf, {
  uploadedDate[uploadedDate == 0] <- NA
  uploadedDate <- unix2POSIXct(uploadedDate)
  metadatedDate[metadatedDate == 0] <- NA
  metadatedDate <- unix2POSIXct(metadatedDate)
  year <- as.numeric(year)
})

# Elimino tutte le righe con entrambi NA alla data di metadata e di upload
param_wdf <- param_wdf[rowSums(is.na(param_wdf[,3:4])) < 2,]

paramAggr_wdf <- ddply(
  param_wdf
  , .(metadatedDate, uploadedDate, domainName, year, countryName, siteLTERCode)
  , summarize
  , parameterNum = length(domainName)
)
paramAggr_wdf$row <- seq(1:nrow(paramAggr_wdf))
paramAggr_df <- reshape(
  paramAggr_wdf
  , direction = "long"
  , varying = 1:2
  , times = colnames(paramAggr_wdf)[1:2]
  , v.names = "submissionDate"
  , idvar = colnames(paramAggr_wdf)[c(3:6, 8)]
  , timevar = "action"
)
paramAggr_df <- paramAggr_df[complete.cases(paramAggr_df),]
paramAggr_df$action <- factor(paramAggr_df$action)
row.names(paramAggr_df) <- NULL

paramAggr_df$totParameters <- unlist(apply(
  paramAggr_df, 1, function(x) {
    if (x[["year"]] == 2012) {
      execQuery(
        'countParameters2012PerSite'
        , dbConnection
        , siteLTERCode = x[["siteLTERCode"]]
        , domainName = x[["domainName"]]
      )
    } else {
      execQuery(
        'countParameters2011PerSite'
        , dbConnection
        , siteLTERCode = x[["siteLTERCode"]]
        , domainName = x[["domainName"]]
      )  
    }
  }
))

```

```{r "siteCounts"}
siteCount    <- execQuery('siteCount', connection = dbConnection)[["siteCount"]]
stationCount <- execQuery('stationCount', connection = dbConnection)[["stationCount"]]
paramCount   <- execQuery('parameterCount', connection = dbConnection)
```


```{r "uploadedStats"}
statsRaw <- matrix(
  with(
    paramAggr_df, {
      c(
        sum(parameterNum[year == 2012 & action == "uploadedDate"])
        , sum(parameterNum[year == 2011 & action == "uploadedDate"])
        , sum(parameterNum[year == 2012 & action == "metadatedDate"])
        , sum(parameterNum[year == 2011 & action == "metadatedDate"])
        , paramCount$Y2012Count
        , paramCount$Y2011Count
        )
      }
    )
  , ncol = 3
  , dimnames = list(
    c("Year2012", "Year2011")
    , c("No. uploaded", "No. metadated", "Total no.")
    )
  )
statsRaw <- addmargins(statsRaw, margin = 1)

statsRaw <- cbind(
  statsRaw
  , "Upload ratio"   = statsRaw[,"No. uploaded"] / statsRaw[,"Total no."]
  , "Metadata ratio" = statsRaw[,"No. metadated"] / statsRaw[,"Total no."]
  )
```


## State of uploading process

* Last updated ```r as.character(Sys.Date())```
* Deadline for data submission: `2013-03-08`
* Days to deadline: ```r difftime(submissionWindowDates$end, Sys.Date(), units = "days")```
* Total number of sites sampled in 2012: ```r siteCount```; sub-sites: ```r stationCount```

Parameters uploaded and metadated:
```{r "xtable",results='asis'}
print(xtable(statsRaw, display = c("s", "d", "d", "d", "f", "f")), type = "html")
```




---

## Aggregated data

```{r "aggrDataByDomain"}
domainAggr_df <- ddply(
  paramAggr_df
  , .(domainName, countryName, action)
  , summarise
  , totalParamCount = sum(parameterNum)
  )
#levels(domainAggr_df$action) <- "Dataset uploaded"
levels(domainAggr_df$action) <- c("Dataset metadated", "Dataset uploaded")

submissionPlot <- ggplot(domainAggr_df, aes(x = countryName, y = totalParamCount, fill = domainName)) +
  geom_bar(stat = "identity") +
  ylab("Total count of parameters submitted") +
  xlab("Country name") +
  ggtitle("A5 data submissions") +
  facet_wrap(~action) +
  theme_bw()
suppressWarnings(print(submissionPlot))
```

---

## Submissions time line trend
 

```{r "timeLineChart", fig.width=14}

paramAggrDate_df <- within(paramAggr_df, {
  submissionDate <- as.Date(submissionDate)
})


# Creo un data.frame che abbia tante righe quanti sono i giorni della finestra di
# sottomissione di A5 (15 febbraio 2013 - 8 marzo 2013) per dominio per azione
tmpRange <- seq(
  from = submissionWindowDates$start
  , to = submissionWindowDates$end
  , by = 1
  )
tmpDomains <- execQuery('domainNames', connection = dbConnection)$domainName
tmpActions <- c("uploadedDate", "metadatedDate")
tmpCountries <- execQuery('countryNames', connection = dbConnection)$countryName
submissionWindow <- expand.grid(
  tmpRange
  , tmpDomains
  , tmpActions
  , tmpCountries
  )
colnames(submissionWindow) <- c("submissionDate", "domainName", "action", "countryName")

submissionWindowParameters <- merge(
  submissionWindow
  , paramAggrDate_df[, colnames(paramAggrDate_df) %in% c("submissionDate", "countryName", "domainName", "action", "parameterNum")]
  , all = TRUE
  )
rm(submissionWindow, list=ls(pattern="^tmp"))

# Assegno 0 a tutti i NA nella colonna parameterNum, necessario per calcolare la somma cumulata
submissionWindowParameters$parameterNum[is.na(submissionWindowParameters$parameterNum)] <- 0

# Aggreghiamoli per giornata di sottomissione in modo che non ci siano più record
# per ciascun sito e data di sottomissione
submissionWindowParameters <- ddply(
  submissionWindowParameters
  , .(domainName, submissionDate, action, countryName)
  , summarise
  , parameterNum  = sum(parameterNum)
)

# ordino per dominio e data
submissionWindowParameters <- submissionWindowParameters[order(submissionWindowParameters$domainName, submissionWindowParameters$submissionDate), ]

# Somma cumulata dei parametri per dominio
submissionWindowParameters <- ddply(
  submissionWindowParameters
  , .(domainName, action, countryName)
  , transform
  , cumParameter = cumsum(parameterNum)
  )

#
submissionWindowParameters$action <- ifelse(submissionWindowParameters$action == "uploadedDate", "Uploaded", "Metadated")

g <- ggplot(submissionWindowParameters) +
  geom_area(aes(x = submissionDate, y = cumParameter, fill = domainName)) +
  ylab("Cumulative count of parameters submitted") +
  xlab("Submission date") +
  ggtitle("Time line of submissions of parameters to A5") +
  facet_grid(action~countryName) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 60, hjust = 1)) +
  theme(legend.position = "bottom")
print(g)
```



```{r "cleanAndQuit", echo=FALSE, results='hide'}
dbDisconnect(dbConnection)
options(gVisOp)
```

